export enum Module {
  DASHBOARD = "DASHBOARD",
  CANDIDATE_AREA = "CANDIDATE_AREA",
  RECRUITMENT = "RECRUITMENT",
  SUPERVISION = "SUPERVISION",
  COMPANY_MANAGEMENT = "COMPANY_MANAGEMENT",
  SUPPORT_PANEL = "SUPPORT_PANEL",
  FINANCE = "FINANCE",
  SALES = "SALES",
  OPERATIONAL = "OPERATIONAL",
  COMPLIANCE = "COMPLIANCE",
  ADMIN_PANEL = "ADMIN_PANEL"
}