export const ROLES_GESTOR = ['RECRUITER', 'RECRUITER_VIP', 'RECRUITER_LEAD', 'COMPANY_ADMIN', 'DEVELOPER', 'SUPER_ADMIN'];
export const ROLES_ADMIN = ['ADMIN_N1', 'ADMIN_N2', 'SUPER_ADMIN', 'DEVELOPER'];
export const ROLES_SUPORTE = ['SUPPORT_N1', 'SUPPORT_N2', 'SUPPORT_N3', 'MODERATOR'];